spec:
  name: finmind
  region: nyc
  features:
    - buildpack-stack=ubuntu-22

  databases:
    - engine: PG
      name: finmind-db
      num_nodes: 1
      size: db-s-dev-database
      version: "16"

  services:
    # ── Backend API ──
    - name: finmind-backend
      dockerfile_path: packages/backend/Dockerfile
      source_dir: /
      http_port: 8000
      instance_count: 1
      instance_size_slug: basic-xxs
      run_command: >-
        sh -c "python -m flask --app wsgi:app init-db &&
        gunicorn -w 2 -k gthread --timeout 120 -b 0.0.0.0:8000 wsgi:app"
      health_check:
        http_path: /health
        initial_delay_seconds: 30
        period_seconds: 15
        timeout_seconds: 5
        success_threshold: 1
        failure_threshold: 3
      envs:
        - key: DATABASE_URL
          scope: RUN_TIME
          value: ${finmind-db.DATABASE_URL}
        - key: REDIS_URL
          scope: RUN_TIME
          type: SECRET
          value: "redis://default:password@finmind-redis:25061"
        - key: JWT_SECRET
          scope: RUN_TIME
          type: SECRET
          value: "CHANGE_ME_IN_PRODUCTION"
        - key: LOG_LEVEL
          scope: RUN_TIME
          value: INFO

    # ── Frontend Static Site ──
    - name: finmind-frontend
      dockerfile_path: app/Dockerfile
      source_dir: /
      http_port: 80
      instance_count: 1
      instance_size_slug: basic-xxs
      build_command: ""
      envs:
        - key: VITE_API_URL
          scope: BUILD_TIME
          value: ${finmind-backend.PUBLIC_URL}
